# Basic
title: 火锅加糖
subtitle: 仗剑行千里，微躯敢一言。<br>曾为大梁客，不负信陵恩。

welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://ccwKevin.club">@Kevin</a>

url: "http://ccwKevin.club"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: https://github.com/wangch6688/wangch6688.github.io
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: wangch6688
    twitter: KingmessCrl
    gplus: 107108267983477358170
    mail: wangch6688@hotmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
